name: coffeeflavor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  dio: ^5.4.0
  get_it: ^7.6.7
  get: ^4.6.5
  chucker_flutter: ^1.6.3
  permission_handler: ^11.0.1
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  easy_localization: ^3.0.3
  url_launcher: ^6.2.5
  infinite_scroll_pagination: ^4.0.0
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  animated_svg: ^2.0.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  pinput: ^2.2.8
  gradient_borders: ^1.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/anim/
    - assets/fonts/
    - assets/i18n/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open_sans/static/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Bold.ttf